/*
 * Facebook Conversions API (for Web)
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FacebookConversionsApiForWeb) {
      root.FacebookConversionsApiForWeb = {};
    }
    root.FacebookConversionsApiForWeb.Content = factory(root.FacebookConversionsApiForWeb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Content model module.
   * @module model/Content
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Content</code>.
   * An object that contain the product IDs associated with the event plus information about the products.
   * @alias module:model/Content
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Content} obj Optional instance to populate.
   * @return {module:model/Content} The populated <code>Content</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('item_price'))
        obj.itemPrice = ApiClient.convertToType(data['item_price'], 'Number');
    }
    return obj;
  }

  /**
   * Product Id
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * number of product
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * Item Price.
   * @member {Number} itemPrice
   */
  exports.prototype.itemPrice = undefined;


  return exports;

}));
