/*
 * Facebook Conversions API (for Web)
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Content'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Content'));
  } else {
    // Browser globals (root is window)
    if (!root.FacebookConversionsApiForWeb) {
      root.FacebookConversionsApiForWeb = {};
    }
    root.FacebookConversionsApiForWeb.CustomData = factory(root.FacebookConversionsApiForWeb.ApiClient, root.FacebookConversionsApiForWeb.Content);
  }
}(this, function(ApiClient, Content) {
  'use strict';

  /**
   * The CustomData model module.
   * @module model/CustomData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CustomData</code>.
   * An object that includes additional business data about the event which can be used for ads delivery optimization. If our predefined object properties don't suit your needs, you can include your own, custom properties. Custom properties can be used with both standard and custom events, and can help you further define custom audiences.
   * @alias module:model/CustomData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CustomData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomData} obj Optional instance to populate.
   * @return {module:model/CustomData} The populated <code>CustomData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('content_name'))
        obj.contentName = ApiClient.convertToType(data['content_name'], 'String');
      if (data.hasOwnProperty('content_category'))
        obj.contentCategory = ApiClient.convertToType(data['content_category'], 'String');
      if (data.hasOwnProperty('content_ids'))
        obj.contentIds = ApiClient.convertToType(data['content_ids'], ['String']);
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], [Content]);
      if (data.hasOwnProperty('content_type'))
        obj.contentType = ApiClient.convertToType(data['content_type'], 'String');
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], 'String');
      if (data.hasOwnProperty('predicted_ltv'))
        obj.predictedLtv = ApiClient.convertToType(data['predicted_ltv'], 'Number');
      if (data.hasOwnProperty('num_items'))
        obj.numItems = ApiClient.convertToType(data['num_items'], 'Number');
      if (data.hasOwnProperty('search_string'))
        obj.searchString = ApiClient.convertToType(data['search_string'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }

  /**
   * A numeric value associated with this event. This could be a monetary value or a value in some other metric.
   * @member {Number} value
   */
  exports.prototype.value = undefined;

  /**
   * The currency for the value specified, if applicable. Currency must be a valid ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217) three digit currency code.
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * The name of the page or product associated with the event.
   * @member {String} contentName
   */
  exports.prototype.contentName = undefined;

  /**
   * The category of the content associated with the event.
   * @member {String} contentCategory
   */
  exports.prototype.contentCategory = undefined;

  /**
   * The content IDs associated with the event, such as product SKUs for items in an AddToCart event: ['ABC123', 'XYZ789']. If content_type is a product, then your content IDs must be an array with a single string value. Otherwise, this array can contain any number of string values.
   * @member {Array.<String>} contentIds
   */
  exports.prototype.contentIds = undefined;

  /**
   * A list of Content objects that contain the product IDs associated with the event plus information about the products. id, quantity, and item_price are available fields.
   * @member {Array.<module:model/Content>} contents
   */
  exports.prototype.contents = undefined;

  /**
   * It should be set to 'product' or 'product_group'. Use 'product', if the keys you send represent products. Sent keys could be content_ids or contents. Use product_group, if the keys you send in content_ids represent product groups. Product groups are used to distinguish products that are identical but have variations such as color, material, size or pattern.
   * @member {String} contentType
   */
  exports.prototype.contentType = undefined;

  /**
   * The order ID for this transaction as a String.
   * @member {String} orderId
   */
  exports.prototype.orderId = undefined;

  /**
   * The predicted lifetime value of a conversion event, as a String.
   * @member {Number} predictedLtv
   */
  exports.prototype.predictedLtv = undefined;

  /**
   * Use only with InitiateCheckout events. The number of items that a user tries to buy during checkout.
   * @member {Number} numItems
   */
  exports.prototype.numItems = undefined;

  /**
   * Use only with Search events. A search query made by a user.
   * @member {String} searchString
   */
  exports.prototype.searchString = undefined;

  /**
   * Use only with CompleteRegistration events. The status of the registration event
   * @member {String} status
   */
  exports.prototype.status = undefined;


  return exports;

}));
