/*
 * Facebook Conversions API (for Web)
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseErrorError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResponseErrorError'));
  } else {
    // Browser globals (root is window)
    if (!root.FacebookConversionsApiForWeb) {
      root.FacebookConversionsApiForWeb = {};
    }
    root.FacebookConversionsApiForWeb.ResponseError = factory(root.FacebookConversionsApiForWeb.ApiClient, root.FacebookConversionsApiForWeb.ResponseErrorError);
  }
}(this, function(ApiClient, ResponseErrorError) {
  'use strict';

  /**
   * The ResponseError model module.
   * @module model/ResponseError
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResponseError</code>.
   * @alias module:model/ResponseError
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponseError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseError} obj Optional instance to populate.
   * @return {module:model/ResponseError} The populated <code>ResponseError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('error'))
        obj.error = ResponseErrorError.constructFromObject(data['error']);
    }
    return obj;
  }

  /**
   * @member {module:model/ResponseErrorError} error
   */
  exports.prototype.error = undefined;


  return exports;

}));
