/*
 * Facebook Conversions API (for Web)
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FacebookConversionsApiForWeb) {
      root.FacebookConversionsApiForWeb = {};
    }
    root.FacebookConversionsApiForWeb.ResponseSuccess = factory(root.FacebookConversionsApiForWeb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ResponseSuccess model module.
   * @module model/ResponseSuccess
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResponseSuccess</code>.
   * @alias module:model/ResponseSuccess
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponseSuccess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseSuccess} obj Optional instance to populate.
   * @return {module:model/ResponseSuccess} The populated <code>ResponseSuccess</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('events_received'))
        obj.eventsReceived = ApiClient.convertToType(data['events_received'], 'Number');
      if (data.hasOwnProperty('messages'))
        obj.messages = ApiClient.convertToType(data['messages'], ['String']);
      if (data.hasOwnProperty('fbtrace_id'))
        obj.fbtraceId = ApiClient.convertToType(data['fbtrace_id'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} eventsReceived
   */
  exports.prototype.eventsReceived = undefined;

  /**
   * @member {Array.<String>} messages
   */
  exports.prototype.messages = undefined;

  /**
   * @member {String} fbtraceId
   */
  exports.prototype.fbtraceId = undefined;


  return exports;

}));
