/*
 * Facebook Conversions API (for Web)
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FacebookConversionsApiForWeb);
  }
}(this, function(expect, FacebookConversionsApiForWeb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EventRequest', function() {
      beforeEach(function() {
        instance = new FacebookConversionsApiForWeb.EventRequest();
      });

      it('should create an instance of EventRequest', function() {
        // TODO: update the code to test EventRequest
        expect(instance).to.be.a(FacebookConversionsApiForWeb.EventRequest);
      });

      it('should have the property data (base name: "data")', function() {
        // TODO: update the code to test the property data
        expect(instance).to.have.property('data');
        // expect(instance.data).to.be(expectedValueLiteral);
      });

      it('should have the property testEventCode (base name: "test_event_code")', function() {
        // TODO: update the code to test the property testEventCode
        expect(instance).to.have.property('testEventCode');
        // expect(instance.testEventCode).to.be(expectedValueLiteral);
      });

      it('should have the property partnerAgent (base name: "partner_agent")', function() {
        // TODO: update the code to test the property partnerAgent
        expect(instance).to.have.property('partnerAgent');
        // expect(instance.partnerAgent).to.be(expectedValueLiteral);
      });

    });
  });

}));
